# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: kosmos200-application

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: centrius-libraries
      url-base: https://github.com/hubelectronics/centrius-libraries.git

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.7.0
      import: true
    - name: centrius-library
      remote: centrius-libraries
      revision: main
      import: true
